<?php
/**
 * @var \Stape\Gtm\Block\Adminhtml\System\Config\SameOrigin\Button\Test $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php $button = $block->getButton(); ?>
<?= $button->toHtml(); ?>
<div id="stape-same-origin-message"></div>
<script type="text/x-magento-init">
    {
        "#<?= $escaper->escapeHtmlAttr($button->getId()); ?>": {
            "Stape_Gtm/js/system/config/same-origin/button/test": {
                "savedPath": "<?= $escaper->escapeJs($block->getSavedPath()); ?>",
                "baseUrl": "<?= $escaper->escapeJs($block->getStoreBaseUrl()); ?>",
                "pathFieldSelector": "#stape_gtm_general_same_origin_path",
                "messageContainer": "#stape-same-origin-message"
            }
        }
    }
</script>
