<?php
/**
 * @var \Stape\Gtm\Block\Adminhtml\System\Config\Webhook\Button\Test $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php $button = $block->getButton(); ?>
<?= $button->toHtml(); ?>
<div id="stape-webhook-message"></div>
<script type="text/x-magento-init">
    {
        "#<?= $escaper->escapeHtmlAttr($button->getId()); ?>": {
            "Stape_Gtm/js/system/config/webhook/button/test": {
                "actionUrl": "<?= $escaper->escapeHtml($block->getActionUrl()); ?>",
                "messageContainer": "#stape-webhook-message"
            }
        }
    }
</script>

