<?php
/**
 * @var \Stape\Gtm\Block\Hyva\ExtraData $block
 * @var \Hyva\Theme\Model\ViewModelRegistry $viewModels
 * @var \Magento\Framework\View\Helper\SecureHtmlRender $secureRenderer
 */
$extraData = [
    'currency' => $block->getCurrencyCode(),
];
$productListViewModel = $viewModels->require(\Hyva\Theme\ViewModel\ProductList::class);
if ($product = $block->getProduct()) {
    foreach (['upsell', 'related'] as $type) {
        $extraData['lists'][] = [
            'item_list_name' => $type,
            'items' => $block->toEventItems($productListViewModel->getLinkedItems($type, $product))
        ];
    }
} else {
    $items = $productListViewModel->getCrosssellItems(
        ...$viewModels->require(\Hyva\Theme\ViewModel\Cart\Items::class)->getCartItems()
    );
    if (!empty($items)) {
        $extraData['lists'][] = [
            'item_list_name' => 'crosssell',
            'items' => $block->toEventItems($items),
        ];
    }
}

?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['type' => 'text/javascript'], <<<JS
    document.addEventListener('DOMContentLoaded', function() {
        window.stapeDataLayer.addExtraData({$block->dataToJson($extraData)});
    })
JS, false); ?>

