<?php declare(strict_types=1);

use Stape\Gtm\Block\Gtm;

/**
 * @var Gtm $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRender $secureRenderer
 */
?>
<?php $dataLayer = $block->getDataLayer(); ?>
<?php if (!empty($block->getContainerId())): ?>
    <?= $block->getGtmSnippetHtml() ?>
<?php endif; ?>

<?php $dataLayer = $block->getDataLayer(); ?>

<?php if ($dataLayer && $block->isDataLayerEnabled()): ?>
    <?php
    $extraData = $block->getExtraData() && $block->getExtraData()->getJson()
        ? $block->getExtraData()->getJson() : '{}';
    ?>
    <?= /* @noEscape */  $secureRenderer->renderTag('script', ['type' => 'module'], <<<JS
        import { Datalayer } from '{$escaper->escapeUrl($block->getViewFileUrl("Stape_Gtm::js/hyva/Datalayer.js"))}';
        window.stapeDataLayer = new Datalayer({
            productItemSelector: '{$escaper->escapeHtml($block->getProductItemSelector())}',
            eventSuffix: '{$escaper->escapeHtml($block->getEventSuffix())}',
            pageType: '{$block->getPageType()}',
            defaultEventData: {$dataLayer->getJson()} || {},
            extraData: {$extraData}
        });
JS, false); ?>
    <?= /* @noEscape */ $block->getChildHtml('stape.gtm.extradata'); ?>
<?php endif; ?>
