<?php declare(strict_types=1);

use Stape\Gtm\Block\Gtm;

/** @var Gtm $block */
?>
<?php $dataLayer = $block->getDataLayer(); ?>
<?php if (!empty($block->getContainerId())): ?>
    <?php if ($block->useCookieKeeper()): ?>
        <?= $block->getChildHtml('stape.gtm.advanced'); ?>
    <?php else: ?>
        <?= $block->getChildHtml('stape.gtm.default'); ?>
    <?php endif; ?>
<?php endif; ?>

<?php $dataLayer = $block->getDataLayer(); ?>

<?php if ($dataLayer && $block->isDataLayerEnabled()): ?>

    <script>
        const eventRegistry = {};
        function pushData(event) {
            <?php // phpcs:disable ?>
            let eventData = <?= $dataLayer->getJson();?> || {};
            <?php // phpcs:enable ?>
            const customer = event?.detail?.data?.customer;
            let customerData;
            if (customer.customerLoggedIn && typeof eventData.user_data === 'undefined') {
                customerData = Object.keys(gtmData).filter((key) => {
                    return key.indexOf('customer') !== 0;
                }).reduce((cur, key) => { return Object.assign(cur, { [key]: gtmData[key] })}, {});
            }

            if (typeof eventData.customer === 'undefined' && customerData && !eventData.user_data) {
                eventData.user_data = customerData;
            }

            window.dataLayer = window.dataLayer || [];

            const isEventAllowed = eventRegistry[eventData.event] !== undefined
                ? !eventRegistry[eventData.event] : true;
            if (isEventAllowed && eventData.ecommerce) {
                window.dataLayer.push({ecommerce: null});
            }

            if (isEventAllowed) {
                window.dataLayer.push(eventData);
            }

            eventRegistry[eventData.event] = true;

            const cartEvents = event?.detail?.data?.cart?.stape_gtm_events;
            if (cartEvents) {
                Object.keys(cartEvents).map(function(eventCode) {
                    const cartEventData = {
                        event: eventCode,
                        ecommerce: cartEvents[eventCode]
                    };

                    if (eventData.user_data) {
                        cartEventData.user_data = eventData.user_data;
                    }

                    window.dataLayer.push(cartEventData);
                });
            }
            event.detail.data.cart.stape_gtm_events = undefined;
        }

        window.addEventListener('private-content-loaded', pushData);
    </script>
<?php endif; ?>
