<?php
/**
 * @var \Stape\Gtm\Block\Gtm $block
 * @var \Magento\Framework\Escaper $escaper
 */
// phpcs:disable
?>
<?php $dataLayer = $block->getDataLayer(); ?>
<?php $extraData = $block->getExtraData(); ?>
<?php if ($block->isDataLayerEnabled()): ?>
    <script>
        window.dataLayer = window.dataLayer || [];
    </script>
    <script type="text/x-magento-init">
        {
            "*": {
                "Stape_Gtm/js/datalayer": {
                    "isUserDataEnabled": <?= $block->isUserDataEnabled() ? 'true' : 'false'; ?>,
                    "data": <?= /* @noEscape */ $dataLayer ? $dataLayer->getJson() : '{}'; ?>,
                    "suffix": "<?= /* @noEscape */ $block->getEventSuffix(); ?>",
                    "pageType": "<?= $escaper->escapeHtml($block->getPageType() ?? ''); ?>",
                    "extraData": <?= /* @noEscape */ $extraData ? $extraData->getJson() : '{}'; ?>,
                    "productItemSelector": "<?= $escaper->escapeHtml($block->getProductItemSelector()); ?>",
                    "useSkuAsItemId": <?= $block->useSkuAsItemId() ? 'true' : 'false'; ?>
                }
            }
        }
    </script>
<?php endif; ?>
<?php if (!empty($block->getContainerId())): ?>
    <?php if ($block->useCookieKeeper()): ?>
        <?= $block->getChildHtml('stape.gtm.advanced'); ?>
    <?php else: ?>
        <?= $block->getChildHtml('stape.gtm.default'); ?>
    <?php endif; ?>
<?php endif; ?>
